name: dtnsim
channels:
  - defaults
dependencies:
  - python>=3.6
  - networkx
  - pandas
  - lxml
  - pytables
  - numpy
  - pyyaml
  - openpyxl
  - xlrd
  - pip
  - sphinx
  - xlsxwriter
  - pip:
    - simpy
    - pydantic==0.13
    - sphinx_bootstrap_theme

